/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutPipelineRouteImport } from './routes/_layout/pipeline'
import { Route as LayoutCoursesIdRouteImport } from './routes/_layout/courses.$id'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPipelineRoute = LayoutPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCoursesIdRoute = LayoutCoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/pipeline': typeof LayoutPipelineRoute
  '/courses/$id': typeof LayoutCoursesIdRoute
}
export interface FileRoutesByTo {
  '/pipeline': typeof LayoutPipelineRoute
  '/': typeof LayoutIndexRoute
  '/courses/$id': typeof LayoutCoursesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/pipeline': typeof LayoutPipelineRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/courses/$id': typeof LayoutCoursesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pipeline' | '/courses/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/pipeline' | '/' | '/courses/$id'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/pipeline'
    | '/_layout/'
    | '/_layout/courses/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pipeline': {
      id: '/_layout/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof LayoutPipelineRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/courses/$id': {
      id: '/_layout/courses/$id'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof LayoutCoursesIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutPipelineRoute: typeof LayoutPipelineRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutCoursesIdRoute: typeof LayoutCoursesIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutPipelineRoute: LayoutPipelineRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutCoursesIdRoute: LayoutCoursesIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
